<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 24 Mar 2025 19:28:24 +0100
 */

$conf['title'] = 'County of Santa Clara Technology Dictionary ';
$conf['sidebar'] = 'Categories';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['captcha']['mode'] = 'text';
$conf['plugin']['captcha']['loginprotect'] = '1';
$conf['tpl']['mindthedark']['theme'] = 'dark';
$conf['plugin']['translation']['dropdown'] = '1';
$conf['plugin']['translation']['redirectstart'] = '1';
$conf['logo'] = 'lib/images/seal_of_santa_clara_county.png';
