<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 13 Mar 2025 01:13:08 +0100
 */

$conf['title'] = 'County of Santa Clara Technology Dictionary ';
$conf['template'] = 'argon';
$conf['sidebar'] = 'Categories';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
