# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 12 Mar 2025 23:21:54 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$RWfzq2ts6Y4eTLdBHzsiWeCZtIn9C4jlw4amy8lmrS2imUMU2yRfi:Aditya Seth:adiseth.seth@gmail.com:admin,user
