# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 12 Mar 2025 23:21:54 +0000
*               @ALL          1
*               @user         8
