<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 16 Apr 2025 19:46:04 +0000
 */

$conf['title'] = 'County of Santa Clara Technology Dictionary ';
$conf['sidebar'] = 'Learning Paths';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['notify'] = 'noreply.santaclaracountywiki@gmail.com';
$conf['registernotify'] = 'noreply.santaclaracountywiki@gmail.com';
$conf['mailfrom'] = 'noreply.santaclaracountywiki@gmail.com';
$conf['mailreturnpath'] = 'noreply.santaclaracountywiki@gmail.com';
$conf['plugin']['captcha']['mode'] = 'audio';
$conf['plugin']['captcha']['loginprotect'] = '1';
$conf['tpl']['mindthedark']['theme'] = 'dark';
$conf['plugin']['translation']['dropdown'] = '1';
$conf['plugin']['translation']['redirectstart'] = '1';
$conf['logo'] = 'lib/images/seal_of_santa_clara_county.png';
$conf['plugin']['smtp']['server'] = 'smtp.gmail.com';
$conf['plugin']['smtp']['port'] = '587';
$conf['plugin']['smtp']['auth'] = '1';
$conf['plugin']['smtp']['user'] = 'noreply.santaclaracountywiki@gmail.com';
$conf['plugin']['smtp']['pass'] = '$sccParagon$82';
$conf['plugin']['smtp']['secure'] = 'tls';
