# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 12 Mar 2025 23:21:54 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$RWfzq2ts6Y4eTLdBHzsiWeCZtIn9C4jlw4amy8lmrS2imUMU2yRfi:Aditya Seth:adiseth.seth@gmail.com:admin,user
testuser3:$2y$10$Gp5e3KOXsVhciFBf3KMDouaID38WQdJ6Gi8PjfW9u7xgYRM5T6kQC:Test User:aseth@ucdavis.edu:user
amywong:$2y$10$FiKp0cmEwR1mi5RrLHBOhukiLFOfQlBXO8lDM6yNo5T/z7CzUYhtm:Amy Wong:amylw@g.ucla.edu:user
annedo:$2y$10$iSwCUoeovJKIgWL2hcr3FOcTlJDcc0IOs4gBHBTOOyoQX0EdA/mfa:Anne Do:doanneda@gmail.com:user
lailaalbalkhi:$2y$10$rcmPpZOSjTuzbhmky3EKMOymTbD0uZMv6mkcqVWsvo7usuXVi0RUa:Laila Albalkhi:albalkhi.laila@gmail.com:user
pranavdulepet:$2y$10$ef1hlXuqUMWU3Jyf2N0lSusxpNTSbIua/qdjtnV36cPnMQmJtofWm:Pranav Dulepet:ps.dulepet@gmail.com:user
tonywang:$2y$10$r6ISJSJfFweyO7yUsLMOjuXL5FSf2CbYCgX5h4.z2HPLUZhtCkm0W:Tony Wang:tonyuu.wang@gmail.com:user
quinnwilson:$2y$10$LjMaqVJrQUIBKXh6OpIYVudsIEFWbEVUDE8eIvOjyHi0eCcl5WG8y:Quinn Wilson:quinn_wilson@berkeley.edu:user
